steps:
- name: gcr.io/falabella-lista-productos-web/fff1e14c-4a2c-48c7-8239-d1a3a8feabc9@sha256:818cf65b15e758a30ec87c5c12d953094fbcc46065f0bed45c1e33238dd7e9a8
  args:
    - '-m'
    - 'rsync'
    - '-d'
    - '-r'
    - 'dags'
    - 'gs://${_GCS_BUCKET}/dags'


